<?php

return [
    'AtomicFragility' => [
        'Vip' => [
            'price' => 100,
            'capabilities' => [
                'kitVip' => true,
                'kitExtra' => false,
                'kitAbsolute' => false,
                'kitFood' => true,
                'kitExp' => false,
                'kitResources' => true,
                'kitResources2' => false,
                'privates' => 4,
                'warps' => 2,
                'saveInventory' => false,
                'saveExp' => true,
                'enterToFullServer' => false,
                'fly' => false,
                'repair' => false,
                'craftingBench' => true,
                'enderChest' => true,
                'eat' => false,
                'heal' => false,
            ],
        ],

        'Extra' => [
            'price' => 300,
            'capabilities' => [
                'kitVip' => true,
                'kitExtra' => true,
                'kitAbsolute' => false,
                'kitFood' => true,
                'kitExp' => true,
                'kitResources' => true,
                'kitResources2' => false,
                'privates' => 6,
                'warps' => 4,
                'saveInventory' => true,
                'saveExp' => true,
                'enterToFullServer' => true,
                'fly' => false,
                'repair' => true,
                'craftingBench' => true,
                'enderChest' => true,
                'eat' => true,
                'heal' => false,
            ],
        ],

        'Absolute' => [
            'price' => 500,
            'capabilities' => [
                'kitVip' => true,
                'kitExtra' => true,
                'kitAbsolute' => true,
                'kitFood' => true,
                'kitExp' => true,
                'kitResources' => true,
                'kitResources2' => true,
                'privates' => 8,
                'warps' => 6,
                'saveInventory' => true,
                'saveExp' => true,
                'enterToFullServer' => true,
                'fly' => true,
                'repair' => true,
                'craftingBench' => true,
                'enderChest' => true,
                'eat' => true,
                'heal' => true,
            ],
        ],
    ]
];
